name: valgrind

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, closed, edited, ready_for_review, auto_merge_enabled]
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
    - name: valgrind check
      run: |
        make DEBUG=1
        valgrind --show-leak-kinds=all -s --leak-check=full --track-origins=yes ./seqperm --upper y --start 1 --end 5 --last 2024,001,1,355 --connectors .,- hi how are you 1>/dev/null
        valgrind --show-leak-kinds=all -s --leak-check=full --track-origins=yes ./seqperm --upper n --start 1 --end 5 --last 2024,001,1,355 --connectors .,- hi how are you 1>/dev/null
        valgrind --show-leak-kinds=all -s --leak-check=full --track-origins=yes ./seqperm --upper y --start 3 --end 3 --last 2024,001,1,355 --connectors .,- hi how are you 1>/dev/null
        valgrind --show-leak-kinds=all -s --leak-check=full --track-origins=yes ./seqperm --upper n --start 3 --end 3 --last 2024,001,1,355 --connectors .,- hi how are you 1>/dev/null
        valgrind --show-leak-kinds=all -s --leak-check=full --track-origins=yes ./seqperm --start 1 --end 10 a b c d e f g h i l 1>/dev/null
